Update nf-wininet-internetcheckconnectiona.md
MicrosoftDocs/sdk-api pull request #1848
Opened 2024-06-28 11:14 UTC by smprocoderz

Added program for demonstration...

2024-06-28 11:19 UTC, smprocoderz commented
Default Agreement

   - (default - no company specified) I have sole ownership of intellectual
   property rights to my Submissions and I am not making Submissions in the
   course of work for my employer.


On Fri, Jun 28, 2024 at 4:45 PM microsoft-github-policy-service[bot] <
***@***.***> wrote:

> @smprocoderz <https://github.com/smprocoderz> please read the following
> Contributor License Agreement(CLA). If you agree with the CLA, please reply
> with the following information.
>
> @microsoft-github-policy-service agree [company="{your company}"]
>
> Options:
>
>    - (default - no company specified) I have sole ownership of
>    intellectual property rights to my Submissions and I am not making
>    Submissions in the course of work for my employer.
>
> @microsoft-github-policy-service agree
>
>
>    - (when company given) I am making Submissions in the course of work
>    for my employer (or my employer has intellectual property rights in my
>    Submissions by contract or applicable law). I have permission from my
>    employer to make Submissions and enter into this Agreement on behalf of my
>    employer. By signing below, the defined term “You” includes me and my
>    employer.
>
> @microsoft-github-policy-service agree company="Microsoft"
>
> Contributor License Agreement Contribution License Agreement
>
> This Contribution License Agreement (*“Agreement”*) is agreed to by the
> party signing below (*“You”*),
> and conveys certain license rights to Microsoft Corporation and its
> affiliates (“Microsoft”) for Your
> contributions to Microsoft open source projects. This Agreement is
> effective as of the latest signature
> date below.
>
>    1. *Definitions*.
>    *“Code”* means the computer software code, whether in human-readable
>    or machine-executable form,
>    that is delivered by You to Microsoft under this Agreement.
>    *“Project”* means any of the projects owned or managed by Microsoft
>    and offered under a license
>    approved by the Open Source Initiative (www.opensource.org).
>    *“Submit”* is the act of uploading, submitting, transmitting, or
>    distributing code or other content to any
>    Project, including but not limited to communication on electronic
>    mailing lists, source code control
>    systems, and issue tracking systems that are managed by, or on behalf
>    of, the Project for the purpose of
>    discussing and improving that Project, but excluding communication
>    that is conspicuously marked or
>    otherwise designated in writing by You as “Not a Submission.”
>    *“Submission”* means the Code and any other copyrightable material
>    Submitted by You, including any
>    associated comments and documentation.
>    2. *Your Submission*. You must agree to the terms of this Agreement
>    before making a Submission to any
>    Project. This Agreement covers any and all Submissions that You, now
>    or in the future (except as
>    described in Section 4 below), Submit to any Project.
>    3. *Originality of Work*. You represent that each of Your Submissions
>    is entirely Your original work.
>    Should You wish to Submit materials that are not Your original work,
>    You may Submit them separately
>    to the Project if You (a) retain all copyright and license information
>    that was in the materials as You
>    received them, (b) in the description accompanying Your Submission,
>    include the phrase “Submission
>    containing materials of a third party:” followed by the names of the
>    third party and any licenses or other
>    restrictions of which You are aware, and (c) follow any other
>    instructions in the Project’s written
>    guidelines concerning Submissions.
>    4. *Your Employer*. References to “employer” in this Agreement include
>    Your employer or anyone else
>    for whom You are acting in making Your Submission, e.g. as a
>    contractor, vendor, or agent. If Your
>    Submission is made in the course of Your work for an employer or Your
>    employer has intellectual
>    property rights in Your Submission by contract or applicable law, You
>    must secure permission from Your
>    employer to make the Submission before signing this Agreement. In that
>    case, the term “You” in this
>    Agreement will refer to You and the employer collectively. If You
>    change employers in the future and
>    desire to Submit additional Submissions for the new employer, then You
>    agree to sign a new Agreement
>    and secure permission from the new employer before Submitting those
>    Submissions.
>    5. *Licenses*.
>
>
>    - *Copyright License*. You grant Microsoft, and those who receive the
>    Submission directly or
>    indirectly from Microsoft, a perpetual, worldwide, non-exclusive,
>    royalty-free, irrevocable license in the
>    Submission to reproduce, prepare derivative works of, publicly
>    display, publicly perform, and distribute
>    the Submission and such derivative works, and to sublicense any or all
>    of the foregoing rights to third
>    parties.
>    - *Patent License*. You grant Microsoft, and those who receive the
>    Submission directly or
>    indirectly from Microsoft, a perpetual, worldwide, non-exclusive,
>    royalty-free, irrevocable license under
>    Your patent claims that are necessarily infringed by the Submission or
>    the combination of the
>    Submission with the Project to which it was Submitted to make, have
>    made, use, offer to sell, sell and
>    import or otherwise dispose of the Submission alone or with the
>    Project.
>    - *Other Rights Reserved*. Each party reserves all rights not
>    expressly granted in this Agreement.
>    No additional licenses or rights whatsoever (including, without
>    limitation, any implied licenses) are
>    granted by implication, exhaustion, estoppel or otherwise.
>
>
>    6. *Representations and Warranties*. You represent that You are
>    legally entitled to grant the above
>    licenses. You represent that each of Your Submissions is entirely Your
>    original work (except as You may
>    have disclosed under Section 3). You represent that You have secured
>    permission from Your employer to
>    make the Submission in cases where Your Submission is made in the
>    course of Your work for Your
>    employer or Your employer has intellectual property rights in Your
>    Submission by contract or applicable
>    law. If You are signing this Agreement on behalf of Your employer, You
>    represent and warrant that You
>    have the necessary authority to bind the listed employer to the
>    obligations contained in this Agreement.
>    You are not expected to provide support for Your Submission, unless
>    You choose to do so. UNLESS
>    REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING, AND EXCEPT FOR THE
>    WARRANTIES
>    EXPRESSLY STATED IN SECTIONS 3, 4, AND 6, THE SUBMISSION PROVIDED
>    UNDER THIS AGREEMENT IS
>    PROVIDED WITHOUT WARRANTY OF ANY KIND, INCLUDING, BUT NOT LIMITED TO,
>    ANY WARRANTY OF
>    NONINFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
>    7. *Notice to Microsoft*. You agree to notify Microsoft in writing of
>    any facts or circumstances of which
>    You later become aware that would make Your representations in this
>    Agreement inaccurate in any
>    respect.
>    8. *Information about Submissions*. You agree that contributions to
>    Projects and information about
>    contributions may be maintained indefinitely and disclosed publicly,
>    including Your name and other
>    information that You submit with Your Submission.
>    9. *Governing Law/Jurisdiction*. This Agreement is governed by the
>    laws of the State of Washington, and
>    the parties consent to exclusive jurisdiction and venue in the federal
>    courts sitting in King County,
>    Washington, unless no federal subject matter jurisdiction exists, in
>    which case the parties consent to
>    exclusive jurisdiction and venue in the  [...]

2024-06-28 11:29 UTC, smprocoderz commented
@microsoft-github-policy-service agree [company="{default"]

I have sole ownership of intellectual property rights to my
Submissions and I am not making Submissions in the course of work for
my employer.

@microsoft-github-policy-service agree

@microsoft-github-policy-service agree company="Microsoft"


On Fri, Jun 28, 2024 at 4:48 PM Suhel Mulla ***@***.***>
wrote:

> Default Agreement
>
>    - (default - no company specified) I have sole ownership of
>    intellectual property rights to my Submissions and I am not making
>    Submissions in the course of work for my employer.
>
>
> On Fri, Jun 28, 2024 at 4:45 PM microsoft-github-policy-service[bot] <
> ***@***.***> wrote:
>
>> @smprocoderz <https://github.com/smprocoderz> please read the following
>> Contributor License Agreement(CLA). If you agree with the CLA, please reply
>> with the following information.
>>
>> @microsoft-github-policy-service agree [company="{your company}"]
>>
>> Options:
>>
>>    - (default - no company specified) I have sole ownership of
>>    intellectual property rights to my Submissions and I am not making
>>    Submissions in the course of work for my employer.
>>
>> @microsoft-github-policy-service agree
>>
>>
>>    - (when company given) I am making Submissions in the course of work
>>    for my employer (or my employer has intellectual property rights in my
>>    Submissions by contract or applicable law). I have permission from my
>>    employer to make Submissions and enter into this Agreement on behalf of my
>>    employer. By signing below, the defined term “You” includes me and my
>>    employer.
>>
>> @microsoft-github-policy-service agree company="Microsoft"
>>
>> Contributor License Agreement Contribution License Agreement
>>
>> This Contribution License Agreement (*“Agreement”*) is agreed to by the
>> party signing below (*“You”*),
>> and conveys certain license rights to Microsoft Corporation and its
>> affiliates (“Microsoft”) for Your
>> contributions to Microsoft open source projects. This Agreement is
>> effective as of the latest signature
>> date below.
>>
>>    1. *Definitions*.
>>    *“Code”* means the computer software code, whether in human-readable
>>    or machine-executable form,
>>    that is delivered by You to Microsoft under this Agreement.
>>    *“Project”* means any of the projects owned or managed by Microsoft
>>    and offered under a license
>>    approved by the Open Source Initiative (www.opensource.org).
>>    *“Submit”* is the act of uploading, submitting, transmitting, or
>>    distributing code or other content to any
>>    Project, including but not limited to communication on electronic
>>    mailing lists, source code control
>>    systems, and issue tracking systems that are managed by, or on behalf
>>    of, the Project for the purpose of
>>    discussing and improving that Project, but excluding communication
>>    that is conspicuously marked or
>>    otherwise designated in writing by You as “Not a Submission.”
>>    *“Submission”* means the Code and any other copyrightable material
>>    Submitted by You, including any
>>    associated comments and documentation.
>>    2. *Your Submission*. You must agree to the terms of this Agreement
>>    before making a Submission to any
>>    Project. This Agreement covers any and all Submissions that You, now
>>    or in the future (except as
>>    described in Section 4 below), Submit to any Project.
>>    3. *Originality of Work*. You represent that each of Your Submissions
>>    is entirely Your original work.
>>    Should You wish to Submit materials that are not Your original work,
>>    You may Submit them separately
>>    to the Project if You (a) retain all copyright and license
>>    information that was in the materials as You
>>    received them, (b) in the description accompanying Your Submission,
>>    include the phrase “Submission
>>    containing materials of a third party:” followed by the names of the
>>    third party and any licenses or other
>>    restrictions of which You are aware, and (c) follow any other
>>    instructions in the Project’s written
>>    guidelines concerning Submissions.
>>    4. *Your Employer*. References to “employer” in this Agreement
>>    include Your employer or anyone else
>>    for whom You are acting in making Your Submission, e.g. as a
>>    contractor, vendor, or agent. If Your
>>    Submission is made in the course of Your work for an employer or Your
>>    employer has intellectual
>>    property rights in Your Submission by contract or applicable law, You
>>    must secure permission from Your
>>    employer to make the Submission before signing this Agreement. In
>>    that case, the term “You” in this
>>    Agreement will refer to You and the employer collectively. If You
>>    change employers in the future and
>>    desire to Submit additional Submissions for the new employer, then
>>    You agree to sign a new Agreement
>>    and secure permission from the new employer before Submitting those
>>    Submissions.
>>    5. *Licenses*.
>>
>>
>>    - *Copyright License*. You grant Microsoft, and those who receive the
>>    Submission directly or
>>    indirectly from Microsoft, a perpetual, worldwide, non-exclusive,
>>    royalty-free, irrevocable license in the
>>    Submission to reproduce, prepare derivative works of, publicly
>>    display, publicly perform, and distribute
>>    the Submission and such derivative works, and to sublicense any or
>>    all of the foregoing rights to third
>>    parties.
>>    - *Patent License*. You grant Microsoft, and those who receive the
>>    Submission directly or
>>    indirectly from Microsoft, a perpetual, worldwide, non-exclusive,
>>    royalty-free, irrevocable license under
>>    Your patent claims that are necessarily infringed by the Submission
>>    or the combination of the
>>    Submission with the Project to which it was Submitted to make, have
>>    made, use, offer to sell, sell and
>>    import or otherwise dispose of the Submission alone or with the
>>    Project.
>>    - *Other Rights Reserved*. Each party reserves all rights not
>>    expressly granted in this Agreement.
>>    No additional licenses or rights whatsoever (including, without
>>    limitation, any implied licenses) are
>>    granted by implication, exhaustion, estoppel or otherwise.
>>
>>
>>    6. *Representations and Warranties*. You represent that You are
>>    legally entitled to grant the above
>>    licenses. You represent that each of Your Submissions is entirely
>>    Your original work (except as You may
>>    have disclosed under Section 3). You represent that You have secured
>>    permission from Your employer to
>>    make the Submission in cases where Your Submission is made in the
>>    course of Your work for Your
>>    employer or Your employer has intellectual property rights in Your
>>    Submission by contract or applicable
>>    law. If You are signing this Agreement on behalf of Your employer,
>>    You represent and warrant that You
>>    have the necessary authority to bind the listed employer to the
>>    obligations contained in this Agreement.
>>    You are not expected to provide support for Your Submission, unless
>>    You choose to do so. UNLESS
>>    REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING, AND EXCEPT FOR
>>    THE WARRANTIES
>>    EXPRESSLY STATED IN SECTIONS 3, 4, AND 6, THE SUBMISSION PROVIDED
>>    UNDER THIS AGREEMENT IS
>>    PROVIDED WITHOUT WARRANTY OF ANY KIND, INCLUDING, BUT NOT LIMITED TO,
>>    ANY WARRANTY OF
>>    NONINFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
>>    7. *Notice to Microsoft*. You agree to notify Microsoft in writing of
>>    any facts or circumstances of which
>>    You later become aware that would make Your representations in this
>>    Agreement inaccurate in any
>>    respect.
>>    8. *Information about Submissions*. You agree that contributions to
>>    Projects and information about
>>    contribut [...]

2024-06-28 11:32 UTC, smprocoderz commented
@microsoft-github-policy-service agree

@microsoft-github-policy-service agree company="default"


On Fri, Jun 28, 2024 at 4:59 PM microsoft-github-policy-service[bot] <
***@***.***> wrote:

> @smprocoderz <https://github.com/smprocoderz> the command you issued was
> incorrect. Please try again.
>
> Examples are:
>
> @microsoft-github-policy-service agree
>
> and
>
> @microsoft-github-policy-service agree company="your company"
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MicrosoftDocs/sdk-api/pull/1848#issuecomment-2196688926>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BISMTREXZFVEVGDCJX4CW4TZJVCLBAVCNFSM6AAAAABKBVG6ZCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCOJWGY4DQOJSGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2026-07-16 16:59 UTC, GrantMeStrength requested changes
The example code has several issues before it can be merged:

1. **Wrong section**: Content is inserted in the remarks area. Move it to the `## -examples` section.
2. **Caption**: "The following code demonstrates how to use above api call." — "above" is informal, "api" should be "API". Suggested: "The following example checks whether an internet connection is available."
3. **`using namespace std;`** — don't use this in Windows SDK examples.
4. **`bool InternetStatus`** — use `BOOL` to match the Windows API return type.
5. **`cout`** — use `printf` or `wprintf` in Win32 SDK examples; iostream is not idiomatic here.

Corrected form:
```cpp
BOOL bConnected = InternetCheckConnectionA("https://www.microsoft.com/", FLAG_ICC_FORCE_CONNECTION, 0);
if (bConnected)
    printf("Internet connection available.\n");
else
    printf("No internet connection. Error: %lu\n", GetLastError());
```

2026-07-17 20:24 UTC, GrantMeStrength commented
@copilot /review

2026-07-17 20:47 UTC, GrantMeStrength requested changes
**Review: Request Changes — Code Quality Issues**

The code sample has several issues that don't meet documentation standards:

1. `bool InternetStatus` should be `BOOL` — the API returns `BOOL`, not C++ `bool`
2. `using namespace std;` is inappropriate for Win32 API documentation samples
3. `cout` is unusual in Win32 code — prefer `printf` or `wprintf` for consistency with other Win32 docs
4. Missing `#pragma comment(lib, "wininet.lib")` or a note about the required library

Also, the example is placed after the Remarks section — it should be in a proper `## Examples` section.

The concept is fine — a simple connectivity check example would be valuable — but please address the style issues to match existing Win32 documentation conventions.

2026-07-19 18:45 UTC, GrantMeStrength commented
Closing this PR — after review, the added demo code doesn't align with the API reference documentation style used in this repo (uses `iostream` and `using namespace std`, which aren't appropriate for Win32 API reference pages). Additionally, this PR has been open for over 2 years without progress. Thank you for the contribution — we appreciate the intent to help document InternetCheckConnectionA.

2026-07-19 18:46 UTC, closed without merging