Missing and errornous info
MicrosoftDocs/sdk-api pull request #243
Opened 2020-05-08 17:08 UTC by zodiacon

The process handle should have PROCESS_VM_OPERATION access mask
The import library seems to be micore.lib (not kernel32.lib)

2020-05-08 17:09 UTC, PRMerger8 commented
@zodiacon : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-05-08 17:40 UTC, Karl-Bridge-Microsoft requested changes
Please revert the req.lib revision. Every other topic in that docset has the same detail, so we need to be consistent across all related topics. You can file a Git Issue for us to track and create a more extensive work item for that specific task if required.

2020-05-11 16:31 UTC, Karl-Bridge-Microsoft approved these changes

2020-05-11 16:31 UTC, Karl-Bridge-Microsoft commented
#sign-off

2020-05-11 16:31 UTC, merged