Expand IWebAuthenticationCoreManagerInterop pages
MicrosoftDocs/sdk-api pull request #254
Opened 2020-05-14 02:28 UTC by metathinker

- Make clear the relationship between the [IWebAuthenticationCoreManagerInterop](https://docs.microsoft.com/en-us/windows/win32/api/webauthenticationcoremanagerinterop/nn-webauthenticationcoremanagerinterop-iwebauthenticationcoremanagerinterop) interface and UWP [WebAuthenticationCoreManager](https://docs.microsoft.com/en-us/uwp/api/windows.security.authentication.web.core.webauthenticationcoremanager?view=winrt-19041).

- Show how to get a IWebAuthenticationCoreManagerInterop reference from a WebAuthenticationCoreManager.

- Show the correlations between ...Interop methods and the corresponding ...CoreManager methods.

2020-05-14 02:28 UTC, PRMerger13 commented
@metathinker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-05-15 02:52 UTC, PRMerger19 commented
@metathinker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-05-17 02:26 UTC, ChrisGuzak commented on sdk-api-src/content/webauthenticationcoremanagerinterop/nf-webauthenticationcoremanagerinterop-iwebauthenticationcoremanagerinterop-requesttokenforwindowasync.md
> +The window to be used as the parent for the window prompting the user for credentials,
owner, not parent. owner/owned is the relationship used in this case, parent child is different.

2020-05-17 02:26 UTC, ChrisGuzak commented on sdk-api-src/content/webauthenticationcoremanagerinterop/nf-webauthenticationcoremanagerinterop-iwebauthenticationcoremanagerinterop-requesttokenwithwebaccountforwindowasync.md
> +The window to be used as the parent for the window prompting the user for credentials,
owner, owner/owned relationship

2020-05-17 02:30 UTC, PRMerger14 commented
@metathinker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-05-17 02:32 UTC, PRMerger14 commented
@metathinker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-05-25 20:35 UTC, ChrisGuzak approved these changes

2020-05-26 23:54 UTC, stevewhims requested changes
Rather than delete the description from the interface topic (`sdk-api-src/content/webauthenticationcoremanagerinterop/index.md`), is there a better description that we can give?

2020-05-27 00:10 UTC, PRMerger8 commented
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-05-27 00:15 UTC, metathinker commented
> Rather than delete the description from the interface topic (`sdk-api-src/content/webauthenticationcoremanagerinterop/index.md`), is there a better description that we can give?

The file `<webauthenticationcoremanagerinterop.h>` only contains the IWebAuthenticationCoreManagerInterop interface, so any description in the main topic for the file (which is the source file you're pointing to) would necessarily duplicate the description in the interface's main topic, in `sdk-api-src/content/webauthenticationcoremanagerinterop/nn-webauthenticationcoremanagerinterop-iwebauthenticationcoremanagerinterop.md`. In fact, in the old version of the 2 files, the description sections did duplicate each other exactly.

That's the reason I deleted the description in the file topic. I wouldn't object to putting it back, however.

2020-05-27 00:17 UTC, PRMerger9 commented
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-05-27 00:22 UTC, PRMerger12 commented
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-05-27 00:22 UTC, PRMerger12 commented
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-05-27 00:27 UTC, stevewhims commented
Looks good, I think that duplication is necessary/unavoidable in this case, and it's ok. I've added that.

Note that links can be tricky, but I made them all site-relative so that the Microsoft Help Viewer works with them.

As for the pre-existing "Type:" sections, there were a number of problems with those, so deleting them was reasonable, but I tend to like the value that those add, and the expectation they set (I'm trying to get them into every topic), so I fixed up the pre-existing problems with them and restored them.

Thanks for your contribution! :)

-Steve

2020-05-27 00:27 UTC, stevewhims approved these changes

2020-05-27 00:28 UTC, merged