[SetFileTime] Remove unclear duplicated information
MicrosoftDocs/sdk-api pull request #997
Opened 2021-12-15 05:37 UTC by glenn-slayden

The exact same text from `lpLastAccessTime` is repeated verbatim for `lpLastWriteTime`.

Since the text in question specifically only mentions `lpLastAccesTime`, it is not clear whether the special input condition applies to the `lpLastWriteTime` parameter or not.

2021-12-15 05:37 UTC, PRMerger15 commented
@glenn-slayden : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-07-06 19:02 UTC, alvinashcraft commented on sdk-api-src/content/fileapi/nf-fileapi-setfiletime.md
> -To prevent file operations using the given handle from modifying the last access time, call
I checked with the product team, and this paragraph should be kept. We should just update "last access time" to "last write time" in this existing paragraph.

2022-07-11 12:29 UTC, alvinashcraft requested changes
Paragraph should be updated instead of removed, according to the product team. See my comment inline. Thanks for finding this issue!

2022-08-09 17:04 UTC, alvinashcraft commented
Hi, @glenn-slayden. I'm checking in to see if you had a chance to look at the proposed change to this PR based on the product team's suggestion? Do you want to move forward with the updated paragraph, or should we close this PR and handle it separately? Thanks again for your contribution and for bringing this issue to our attention.

2022-08-23 17:39 UTC, glenn-slayden commented
@alvinashcraft  Please go ahead and make the changes in any way you see fit. I do not need to supervise the PR. Thanks,

Glenn

2022-08-30 18:46 UTC, alvinashcraft commented
Hi @glenn-slayden. I just checked in the changes to our internal repo. It should sync to the public repo and the live site shortly. Thanks again for your contribution here. I'm going to close this PR, but feel free to circle back if you have any comments.

2022-08-30 18:46 UTC, closed without merging